language: android
android:
   components:
   - tools
   - tools #Running this twice get's the latest build tools (https://github.com/codepath/android_guides/wiki/Setting-up-Travis-CI)
   - platform-tools
   - android-28
   - build-tools-28.0.3
   - extra
   licenses:
   - 'android-sdk-license-.+'

jdk: oraclejdk8

notifications:
  email: false

sudo: required #The build runs out of memory and is killed if we use the container system

before_install:
  - yes | sdkmanager "platforms;android-28"

script:
  - ./gradlew clean build
  - ./gradlew test
